import { createHash } from 'node:crypto';
import type { FirewallAddressEntry, FirewallSettings } from '@prisma/client';
import { FirewallSetKind } from '@prisma/client';

export const NFT_TABLE_NAME = 'nginx_warden_filter';

/** Sanitize CrowdSec set names for nft (letters, digits, underscore only). */
export function sanitizeNftIdentifier(name: string, fallback: string): string {
  const s = name.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^([0-9])/, '_$1');
  return s.length > 0 ? s : fallback;
}

function elementsList(cidrs: string[]): string {
  if (cidrs.length === 0) return '';
  return `elements = { ${cidrs.join(', ')} }`;
}

function byKind(entries: FirewallAddressEntry[], kind: FirewallSetKind): string[] {
  return entries.filter((e) => e.kind === kind).map((e) => e.cidr.trim());
}

/**
 * Render a full nftables ruleset for `table inet nginx_warden_filter`.
 * CrowdSec firewall bouncer is expected to add IPs to the crowdsec_* sets (timeout-capable, initially empty).
 */
export function renderNftablesRuleset(
  settings: FirewallSettings,
  entries: FirewallAddressEntry[]
): string {
  const trusted4 = byKind(entries, FirewallSetKind.trusted_ipv4);
  const trusted6 = byKind(entries, FirewallSetKind.trusted_ipv6);
  const deny4 = byKind(entries, FirewallSetKind.local_deny_ipv4);
  const deny6 = byKind(entries, FirewallSetKind.local_deny_ipv6);

  const cs4 = sanitizeNftIdentifier(settings.crowdsecNftSetV4, 'crowdsec_blacklists');
  const cs6 = sanitizeNftIdentifier(settings.crowdsecNftSetV6, 'crowdsec6_blacklists');

  const publicPorts = [...new Set(settings.publicTcpPorts)].filter((p) => p > 0 && p < 65536).sort((a, b) => a - b);
  const portSet = publicPorts.length > 0 ? `{ ${publicPorts.join(', ')} }` : '{ }';

  const t4 = elementsList(trusted4);
  const t6 = elementsList(trusted6);
  const d4 = elementsList(deny4);
  const d6 = elementsList(deny6);

  const lines: string[] = [
    '#!/usr/sbin/nft -f',
    '# Generated by Nginx Warden — do not edit by hand',
    `# Apply deletes any existing table first (see firewall.service)`,
    `table inet ${NFT_TABLE_NAME} {`,
    `  set trusted_ipv4 {`,
    `    type ipv4_addr`,
    `    flags interval`,
    trusted4.length > 0 ? `    ${elementsList(trusted4)}` : '',
    `  }`,
    `  set trusted_ipv6 {`,
    `    type ipv6_addr`,
    `    flags interval`,
    trusted6.length > 0 ? `    ${elementsList(trusted6)}` : '',
    `  }`,
    `  set local_deny_ipv4 {`,
    `    type ipv4_addr`,
    `    flags interval`,
    deny4.length > 0 ? `    ${elementsList(deny4)}` : '',
    `  }`,
    `  set local_deny_ipv6 {`,
    `    type ipv6_addr`,
    `    flags interval`,
    deny6.length > 0 ? `    ${elementsList(deny6)}` : '',
    `  }`,
    `  set ${cs4} {`,
    `    type ipv4_addr`,
    `    flags interval, timeout`,
    `  }`,
    `  set ${cs6} {`,
    `    type ipv6_addr`,
    `    flags interval, timeout`,
    `  }`,
    `  chain input {`,
    `    type filter hook input priority filter; policy drop;`,
    `    iif lo accept`,
    `    ct state established,related accept`,
    `    meta nfproto ipv4 ip saddr @trusted_ipv4 accept`,
    `    meta nfproto ipv6 ip6 saddr @trusted_ipv6 accept`,
    `    meta nfproto ipv4 ip saddr @${cs4} drop`,
    `    meta nfproto ipv6 ip6 saddr @${cs6} drop`,
    `    meta nfproto ipv4 ip saddr @local_deny_ipv4 drop`,
    `    meta nfproto ipv6 ip6 saddr @local_deny_ipv6 drop`,
    `    meta nfproto ipv4 tcp dport ${portSet} accept`,
    `    meta nfproto ipv6 tcp dport ${portSet} accept`,
    `  }`,
    `}`,
  ];

  return lines.filter((l) => l !== '').join('\n') + '\n';
}

export function checksumRuleset(content: string): string {
  return createHash('sha256').update(content, 'utf8').digest('hex');
}
