version: "3.9"

services:
  mailwarden:
    image: golang:1.23
    working_dir: /src
    command: ["go", "run", "./cmd/mailwarden", "-config", "./configs/mailwarden.example.yaml", "-listen", ":8080"]
    volumes:
      - ../../:/src
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - rspamd

  policy-worker:
    image: golang:1.23
    working_dir: /src
    command: ["go", "run", "./cmd/policy-worker"]
    volumes:
      - ../../:/src
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: mailwarden
      POSTGRES_USER: mailwarden
      POSTGRES_PASSWORD: mailwarden
    ports:
      - "15433:5432"

  redis:
    image: redis:7
    ports:
      - "16379:6379"

  rspamd:
    image: rspamd/rspamd:3.10
    ports:
      - "11334:11334"

  clamav:
    image: clamav/clamav:latest
    ports:
      - "3310:3310"
