#!/bin/bash

################################################################################
# Nginx Warden - Update Script
# Description: Update source code, rebuild and restart services
# Version: 1.0.0
################################################################################

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
BACKEND_DIR="$PROJECT_DIR/apps/api"
FRONTEND_DIR="$PROJECT_DIR/apps/web"
LOG_FILE="/var/log/nginx-warden-ui-update.log"

# Database configuration
DB_CONTAINER_NAME="nginx-warden-postgres"

# Logging functions
log() {
    echo -e "${GREEN}[$(date '+%Y-%m-%d %H:%M:%S')]${NC} $1" | tee -a "$LOG_FILE"
}

error() {
    echo -e "${RED}[ERROR]${NC} $1" | tee -a "$LOG_FILE"
    exit 1
}

warn() {
    echo -e "${YELLOW}[WARN]${NC} $1" | tee -a "$LOG_FILE"
}

info() {
    echo -e "${BLUE}[INFO]${NC} $1" | tee -a "$LOG_FILE"
}

# Check if running as root
if [[ "${EUID}" -ne 0 ]]; then
   error "This script must be run as root (use sudo)"
fi

log "=================================="
log "Nginx Warden Update Started"
log "=================================="

# Ports: deploy writes /etc/nginx-warden/ports.env; legacy installs infer once and persist.
# This script never overwrites apps/api/.env (secrets, DATABASE_URL, PORT, CORS stay intact).
API_PORT=3001
UI_PORT=8088
if [ -f /etc/nginx-warden/ports.env ]; then
    set -a
    # shellcheck disable=SC1091
    source /etc/nginx-warden/ports.env
    set +a
    API_PORT="${WARDEN_API_PORT:-3001}"
    UI_PORT="${WARDEN_UI_PORT:-8088}"
else
    if [ -f "${BACKEND_DIR}/.env" ]; then
        _p=$(grep -E '^PORT=' "${BACKEND_DIR}/.env" | head -1 | cut -d= -f2- | tr -d '"' | tr -d "'" | tr -d ' ')
        [ -n "${_p}" ] && API_PORT="${_p}"
    fi
    if [ -f /etc/systemd/system/nginx-warden-frontend.service ]; then
        _u=$(grep -oE '\-\-port[[:space:]]+[0-9]+' /etc/systemd/system/nginx-warden-frontend.service | awk '{print $2}' | head -1)
        [ -n "${_u}" ] && UI_PORT="${_u}"
    fi
    mkdir -p /etc/nginx-warden
    {
        echo "# Generated by scripts/update.sh — persisted for health checks and future runs"
        echo "WARDEN_API_PORT=${API_PORT}"
        echo "WARDEN_UI_PORT=${UI_PORT}"
        if [ -f "${BACKEND_DIR}/.env" ]; then
            _dburl=$(grep -E '^DATABASE_URL=' "${BACKEND_DIR}/.env" | head -1 | cut -d= -f2- | tr -d '"' | tr -d "'")
            _dp=$(echo "${_dburl}" | sed -n 's/.*@[^/@]*:\([0-9]*\)\/.*/\1/p')
            [ -n "${_dp}" ] && echo "WARDEN_DB_HOST_PORT=${_dp}"
            _cu=$(grep -E '^CROWDSEC_LAPI_URL=' "${BACKEND_DIR}/.env" | head -1 | cut -d= -f2- | tr -d '"' | tr -d "'")
            _cp=$(echo "${_cu}" | sed -n 's/.*127\.0\.0\.1:\([0-9]*\).*/\1/p')
            if [ -n "${_cp}" ]; then
                echo "CROWDSEC_LAPI_PORT=${_cp}"
            else
                echo "CROWDSEC_LAPI_PORT=9091"
            fi
        else
            echo "CROWDSEC_LAPI_PORT=9091"
        fi
    } > /etc/nginx-warden/ports.env
    chmod 644 /etc/nginx-warden/ports.env
    log "Created /etc/nginx-warden/ports.env from existing configuration (legacy install)"
fi
log "Using API_PORT=${API_PORT} UI_PORT=${UI_PORT} (from /etc/nginx-warden/ports.env or inferred; .env is not modified)"

# Check if services exist
if ! systemctl list-unit-files | grep -q nginx-warden-backend.service; then
    error "Backend service not found. Please run deploy.sh first."
fi

if ! systemctl list-unit-files | grep -q nginx-warden-frontend.service; then
    error "Frontend service not found. Please run deploy.sh first."
fi

# Check if database container exists
if ! docker ps -a | grep -q "${DB_CONTAINER_NAME}"; then
    error "Database container '${DB_CONTAINER_NAME}' not found. Please run deploy.sh first."
fi

# Step 1: Check prerequisites
log "Step 1/6: Checking prerequisites..."

if ! command -v curl &> /dev/null || ! command -v wget &> /dev/null || ! command -v openssl &> /dev/null || ! command -v python3 &> /dev/null || ! command -v git &> /dev/null || ! command -v gpg &> /dev/null || ! command -v ip &> /dev/null; then
    warn "Installing base packages: openssl, curl, wget, ca-certificates, python3, git, gnupg, iproute2..."
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq >> "$LOG_FILE" 2>&1 || true
    apt-get install -y --no-install-recommends openssl curl wget ca-certificates python3 git gnupg iproute2 >> "$LOG_FILE" 2>&1 || error "Failed to install base packages (apt)"
    log "✓ Base packages installed"
else
    log "✓ Base packages present (openssl, curl, wget, python3, git, gnupg, ca-certificates)"
fi

if ! command -v htpasswd &> /dev/null; then
    warn "htpasswd not found. Installing apache2-utils..."
    apt-get install -y apache2-utils >> "$LOG_FILE" 2>&1 || error "Failed to install apache2-utils"
    log "✓ htpasswd installed successfully"
else
    log "✓ htpasswd $(htpasswd -v 2>&1 | head -n1 | awk '{print $3}') detected"
fi


# Check Node.js
if ! command -v node &> /dev/null; then
    error "Node.js not found. Please install Node.js 18+ first."
fi

# Check pnpm
if ! command -v pnpm &> /dev/null; then
    error "pnpm not found. Please install pnpm first."
fi

# Check Docker
if ! command -v docker &> /dev/null; then
    error "Docker not found. Please install Docker first."
fi

log "✓ Prerequisites check passed"

# shellcheck source=lib/warden-access-ip.sh
source "${SCRIPT_DIR}/lib/warden-access-ip.sh"
warden_resolve_access_ips_and_cors "${UI_PORT}"
log "ACCESS_IP=${ACCESS_IP} (LAN first; set WARDEN_ACCESS_IP in /etc/nginx-warden/ports.env to override). If login fails, add http://${ACCESS_IP}:${UI_PORT} to CORS (Fleet → Configuration) or apps/api/.env"

# Step 2: Stop services before update
log "Step 2/6: Stopping services for update..."

# Stop backend service
if systemctl is-active --quiet nginx-warden-backend.service; then
    systemctl stop nginx-warden-backend.service
    log "✓ Backend service stopped"
else
    warn "Backend service was not running"
fi

# Stop frontend service
if systemctl is-active --quiet nginx-warden-frontend.service; then
    systemctl stop nginx-warden-frontend.service
    log "✓ Frontend service stopped"
else
    warn "Frontend service was not running"
fi

# Step 3: Update dependencies and build backend (does not modify apps/api/.env — DB data and secrets unchanged)
log "Step 3/6: Building backend..."

cd "${PROJECT_DIR}"

# Update monorepo dependencies
log "Updating monorepo dependencies..."
pnpm install >> "${LOG_FILE}" 2>&1 || error "Failed to update monorepo dependencies"

cd "${BACKEND_DIR}"

# Start database if not running
if ! docker ps | grep -q "${DB_CONTAINER_NAME}" 2>/dev/null; then
    log "Starting database container..."
    docker start "${DB_CONTAINER_NAME}" 2>/dev/null || warn "Could not start database container"
    sleep 3
fi

# Generate Prisma client
log "Generating Prisma client..."
pnpm prisma generate >> "$LOG_FILE" 2>&1 || error "Failed to generate Prisma client"

# Run database migrations
log "Running database migrations..."
cd "${BACKEND_DIR}"
pnpm prisma migrate deploy >> "$LOG_FILE" 2>&1 || error "Failed to run migrations"

# Seed database safely (only create missing data, preserve existing)
log "Seeding database safely..."
cd "${BACKEND_DIR}"
pnpm ts-node prisma/seed-safe.ts >> "$LOG_FILE" 2>&1 || warn "Failed to seed database safely"

# Build backend
log "Building backend..."
cd "${BACKEND_DIR}"
pnpm build >> "${LOG_FILE}" 2>&1 || error "Failed to build backend"

log "✓ Backend build completed"

# Step 4: Build frontend
log "Step 4/6: Building frontend..."

cd "${FRONTEND_DIR}"

# Avoid baking a single public IP into the JS bundle; runtime resolves API host from the browser URL.
# Opt out with VITE_API_USE_FIXED=true and VITE_API_URL=… for a separate API origin.
if [ -f ".env" ] && ! grep -q "^VITE_API_USE_FIXED=true" ".env" 2>/dev/null; then
  if grep -q "^VITE_API_URL=" ".env"; then
    sed -i 's|^VITE_API_URL=.*|VITE_API_URL=auto|' ".env"
  fi
  log "✓ Frontend .env: VITE_API_URL=auto (API uses same hostname as the page unless VITE_API_USE_FIXED=true)"
fi

# Clean previous build
if [ -d "dist" ]; then
    log "Cleaning previous frontend build..."
    rm -rf dist
fi

# Build frontend
log "Building frontend..."
cd "${FRONTEND_DIR}"
pnpm build >> "${LOG_FILE}" 2>&1 || error "Failed to build frontend"

# CSP uses ACCESS_IP (resolved at start; LAN/private first)
log "Updating Content Security Policy with access IP: ${ACCESS_IP}..."
sed -i "s|__API_URL__|http://${ACCESS_IP}:${API_PORT} http://127.0.0.1:${API_PORT} http://localhost:${API_PORT}|g" "${FRONTEND_DIR}/dist/index.html"
sed -i "s|__WS_URL__|ws://${ACCESS_IP}:* ws://127.0.0.1:* ws://localhost:*|g" "${FRONTEND_DIR}/dist/index.html"

log "✓ Frontend build completed"

# Step 5: Restart services
log "Step 5/6: Starting services..."

# Database should already be running from Step 3, just verify
if ! docker ps | grep -q "${DB_CONTAINER_NAME}"; then
    error "Database container stopped unexpectedly. Please check Docker status."
else
    log "✓ Database container is running"
fi

# Start backend service
systemctl start nginx-warden-backend.service || error "Failed to start backend service"
sleep 3
if ! systemctl is-active --quiet nginx-warden-backend.service; then
    error "Backend service failed to start. Check logs: journalctl -u nginx-warden-backend.service"
fi
log "✓ Backend service started"

# Start frontend service
systemctl start nginx-warden-frontend.service || error "Failed to start frontend service"
sleep 3
if ! systemctl is-active --quiet nginx-warden-frontend.service; then
    error "Frontend service failed to start. Check logs: journalctl -u nginx-warden-frontend.service"
fi
log "✓ Frontend service started"

# Update nginx configuration (copy backup; restore on failure — never leave nginx without a valid config)
ORIGINAL_FILE_NGINX="/etc/nginx/nginx.conf"
BACKUP_FILE="${ORIGINAL_FILE_NGINX}.bak-update-$(date +%Y%m%d%H%M%S)"
if [ -f "$PROJECT_DIR/config/nginx.conf" ]; then
    if [ -f "$ORIGINAL_FILE_NGINX" ]; then
        cp -a "$ORIGINAL_FILE_NGINX" "${BACKUP_FILE}" || warn "Could not backup nginx.conf"
        log "✓ Nginx config backed up to ${BACKUP_FILE}"
    fi
    if ! cp "$PROJECT_DIR/config/nginx.conf" "${ORIGINAL_FILE_NGINX}"; then
        error "Failed to copy nginx config"
    fi
    if ! nginx -t >> "$LOG_FILE" 2>&1; then
        if [ -f "${BACKUP_FILE}" ]; then
            cp -a "${BACKUP_FILE}" "${ORIGINAL_FILE_NGINX}" || warn "Failed to restore nginx.conf from backup"
            log "✓ Restored previous nginx.conf after failed nginx -t"
        fi
        error "Nginx configuration test failed. Previous config restored if backup existed. Check logs: tail -f $LOG_FILE"
    fi
    systemctl reload nginx || error "Failed to reload nginx"
    log "✓ Nginx reloaded"
else
    error "Nginx config not found in $PROJECT_DIR/config/nginx.conf"
fi

# Ensure nginx is running
if ! systemctl is-active --quiet nginx; then
    systemctl start nginx || error "Failed to start nginx"
fi
log "✓ Nginx is running"

# CrowdSec: if engine is installed but apps/api/.env has no usable CROWDSEC_API_KEY (e.g. old upgrade), auto-fix
if [ "${WARDEN_SKIP_CROWDSEC:-0}" != "1" ] && [ -f /etc/crowdsec/config.yaml ] && command -v cscli >/dev/null 2>&1; then
    _ck=$(grep -E '^CROWDSEC_API_KEY=' "${BACKEND_DIR}/.env" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"' | tr -d "'" | tr -d ' ')
    if [ -z "${_ck}" ] || [ "${#_ck}" -lt 8 ]; then
        log "CrowdSec: registering LAPI bouncers and apps/api/.env (scripts/crowdsec-autoconfigure.sh)..."
        export BACKEND_DIR PROJECT_DIR
        export CROWDSEC_LAPI_PORT="${CROWDSEC_LAPI_PORT:-9091}"
        bash "${PROJECT_DIR}/scripts/crowdsec-autoconfigure.sh" >> "$LOG_FILE" 2>&1 || warn "CrowdSec autoconfigure failed (see ${LOG_FILE})"
    fi
fi

# Step 6: Health check and summary
log "Step 6/6: Performing health checks..."

# Health check with retries
log "Performing health checks..."
sleep 5

# Backend health check
BACKEND_HEALTHY=false
for i in {1..10}; do
    if curl -fsS --connect-timeout 5 --max-time 15 "http://localhost:${API_PORT}/api/health" | grep -q "success"; then
        BACKEND_HEALTHY=true
        break
    fi
    sleep 2
done

if [ "$BACKEND_HEALTHY" = true ]; then
    log "✅ Backend health check: PASSED"
else
    warn "⚠️  Backend health check: FAILED (check logs: tail -f /var/log/nginx-warden-backend.log)"
fi

# Frontend health check
FRONTEND_HEALTHY=false
for i in {1..5}; do
    if curl -fsS --connect-timeout 5 --max-time 15 "http://localhost:${UI_PORT}" | grep -q "<!doctype html"; then
        FRONTEND_HEALTHY=true
        break
    fi
    sleep 2
done

if [ "$FRONTEND_HEALTHY" = true ]; then
    log "✅ Frontend health check: PASSED"
else
    warn "⚠️  Frontend health check: FAILED (check logs: tail -f /var/log/nginx-warden-frontend.log)"
fi

# Final Summary
log ""
log "=================================="
log "Update Completed Successfully!"
log "=================================="
log ""
log "📋 Updated Components:"
log "  • Backend API: Rebuilt and restarted"
log "  • Frontend UI: Rebuilt and restarted"
log "  • Database: Migrations applied, missing data created (existing data preserved)"
log ""
log "🌐 Services Status:"
log "  • Backend API: http://${ACCESS_IP}:${API_PORT}"
log "  • Frontend UI: http://${ACCESS_IP}:${UI_PORT}"
log "  • Database: Running in Docker container"
log ""
log "📝 Manage Services:"
log "  Backend:    systemctl {start|stop|restart|status} nginx-warden-backend"
log "  Frontend:   systemctl {start|stop|restart|status} nginx-warden-frontend"
log "  Database:   docker {start|stop|restart} ${DB_CONTAINER_NAME}"
log ""
log "📊 View Logs:"
log "  Backend:    tail -f /var/log/nginx-warden-backend.log"
log "  Frontend:   tail -f /var/log/nginx-warden-frontend.log"
log "  Database:   docker logs -f ${DB_CONTAINER_NAME}"
log "  Update:     tail -f ${LOG_FILE}"
log ""
log "🔐 Access the portal at: http://${ACCESS_IP}:${UI_PORT}"
log ""
log "Update log saved to: ${LOG_FILE}"
log "=================================="
